## Core python programming 

In [ ]:
# =============TYPES OF VARIABLES ( INT , FLOAT, STRING, BOOL)================

# int - 
x=2

In [ ]:
x

In [ ]:
type(x)

In [ ]:
# float -
y = 4.6

In [ ]:
y

In [ ]:
type(y)

In [ ]:
# string - 
z = 'hello'

In [ ]:
z

In [ ]:
z1 = "hi"

In [ ]:
z1
print(z1)

In [ ]:
# bool // logical -
g = 'True'

In [ ]:
g

In [ ]:
i = "False"

In [ ]:
i

In [ ]:
a2=45

In [ ]:
b2=56

In [ ]:
print(a2)
print(b2)

In [ ]:
a2
b2

In [ ]:
# ================== USING VARIABLES =======================

# Arithmetic -
A = 10
B = 5

In [ ]:
C = A + B

In [ ]:
D = B/A

In [ ]:
E = A*B

In [ ]:
F = B-A

In [ ]:
C

In [ ]:
D

In [ ]:
E

In [ ]:
F

In [ ]:
# why is it better to use print() // (ANS) - all o/p will display one time 
print(C)
print(D)
print(E)
print(F)

In [ ]:
# How to run the square root operation - 
import math # math is the module which you are importing

In [ ]:
math.sqrt(16) # 16 is the argument of the sqrt function

In [ ]:
math.sqrt(A) #A=10 which we declare at begining

In [ ]:
round(math.sqrt(A))

In [ ]:
# lets working with string 
greeting = "hello"
name = "amxwam"

In [ ]:
message = greeting + name
print(message)

In [ ]:
name = " amxwam"
message = greeting + name
message

In [ ]:
# ================ BOOL VARIABLES AND OPERATORS ====================
4<5

In [ ]:
10>100

In [ ]:
# <
# >
# <=
# >=
# and
# or
# not

In [ ]:
result = 4<5

In [ ]:
result

In [ ]:
type(result)

In [ ]:
print(type(result))

In [ ]:
result2 = 5>1

In [ ]:
result2

In [ ]:
result3 = not(5>1)

In [ ]:
result3

In [ ]:
result or result2 or result3

In [ ]:
result2 and result3

In [ ]:
# =================== WHILE LOOP =========================

# what is while loop why used for - lets discuss that---

# while(condition){   # checking the condition if the conditiong is true then execute the loop and it keep continue thats why it called as loop
#     executable code1                        # if the condition is false then print to code4 
#     executable code2
#     executable code3
# }
# executable code4

In [ ]:
# === python is indentation based program & no need to required 
# very important you have to check the indentataion & need to maintain properly
# python there is no curly braces
# --------------------------------------------------------------

#while condition:
#    executable code1
#    executable code2
#    executable code3
#executable code4

In [2]:
num = 12
while num<11:
    print(num)
    num = num+1
print('END OF THE PROGRAM')

END OF THE PROGRAM


In [ ]:
count = 13
while count<12:
    print(count)
    count = count + 1
print("End the loop")

In [1]:
#count = 22  #how to print infinite loop
#while count>12: # 22>12
#    print(count)
#    count = count + 1
#print("End the loop")

In [3]:
# ==================== FOR LOOP ==============================

# i define as iteration
for i in range(2):  # while loop we check the condition
    print('Hello python')

Hello python
Hello python


In [4]:
for i in range(5):
    print("Hello python:", i)
    print('welcome to amxwam')
    print('hi')

Hello python: 0
welcome to amxwam
hi
Hello python: 1
welcome to amxwam
hi
Hello python: 2
welcome to amxwam
hi
Hello python: 3
welcome to amxwam
hi
Hello python: 4
welcome to amxwam
hi


In [5]:
for i in range(7):
    print("Hello python:", i)

Hello python: 0
Hello python: 1
Hello python: 2
Hello python: 3
Hello python: 4
Hello python: 5
Hello python: 6


In [6]:
#Another way
mylist = [10,100,1000,2000]

In [7]:
mylist

[10, 100, 1000, 2000]

In [8]:
for j in mylist:
    print('jj is equal to :', j)

jj is equal to : 10
jj is equal to : 100
jj is equal to : 1000
jj is equal to : 2000


In [ ]:
range(5)  #very quick way to creat a set of 5 numbers

In [ ]:
list(range(5)) #what actually range 5 does

In [13]:
# ================= IF STATEMENT ======================
# -----(-2),(-1),(0),(1),(2)------------

import numpy as np # numpy is package is a scientific computation
from numpy.random import randn

In [25]:
randn()

-0.39802927821091155

In [26]:
# -----(-2),(-1),(0),(1),(2)------------

x = randn()
if x>1:   # if is the keyword then use condition & if the condition is true then code got executed and keep going down
    answer = "Greater then 1"
print(x)
#print(answer) 

0.35081350259317573


In [29]:
# -----(-2),(-1),(0),(1),(2)------------

answer = None
x = randn()
if x>1:   # if is the keyword then use condition & if the condition is true then code got executed and keep going down
    answer = "Greater then 1"
print(x)
print(answer) 

-1.9944878994033797
None


In [38]:
# ========== IF-ELSE STATEMENT ====================
# -----(-2),(-1),(0),(1),(2)------------

answer = None
x = randn() 
if x>1:   # if is the keyword then use condition & if the condition is true then code got executed and keep going down
    answer = "Greater then 1"
else:
    answer = "Less then 1"
print(x)
print(answer) 

-0.41124936555151376
Less then 1


In [44]:
# -----(-2),(-1),(0),(1),(2)------------

#================ NESTED STATEMENTS / CHAIN STATEMENT =======================

answer = None
x = randn()

if x>1:   # if is the keyword then use condition & if the condition is true then code got executed and keep going down
    answer = "Greater then 1"
else:
    if x >= -1:
        answer = "Between -1 and 1"
    else:
        answer = "Less then -1"
        
print(x)
print(answer) 

-0.6457572317201399
Between -1 and 1


In [45]:
# -----(-2),(-1),(0),(1),(2)------------

#================ ELIF STATEMENT =======================

answer = None
x = randn()

if x>1:   # if is the keyword then use condition & if the condition is true then code got executed and keep going down
    answer = "Greater then 1"
elif x >= -1:
        answer = "Between -1 and 1"
else:
        answer = "Less then -1"
        
print(x)
print(answer) 

1.1976434149945772
Greater then 1


In [47]:
# ============ CODE INDENTATION IN PYTHON =================

# -----(-2),(-1),(0),(1),(2)------------

#================ ELIF STATEMENT =======================

answer = None
x = randn()

if x>1:   # if is the keyword then use condition & if the condition is true then code got executed and keep going down
    answer = "Greater then 1"
elif x >= -1:
        answer = "Between -1 and 1"
else:
        answer = "Less then -1"
        print('Aspired datascientist')
print('Aspired Datascientist')
print(x)
print(answer) 

Aspired datascientist
Aspired Datascientist
-1.4394872113046466
Less then -1


### what we learned so far -
1.Type of variable
2.Using variable
3.Logical variable and operator
4.while loop
5.For loop
6.if statement, if _ else statement, elif statement
7.random variables: randn()
8.numpy 

### Fundamentals of python which are used in datascience - 

In [ ]:
# List - ordered sequeence of elements & always start with 0
# you can decleare the mixed datatype variables
# List closed in [] bracket

MyFirstList = [5, 50, 67, 2020]

In [ ]:
MyFirstList

In [ ]:
type(MyFirstList)

In [ ]:
MysecondList = [2, 5.0,'AMXWAM',True,40+67j] #multiple datatypes you can declared in the list

In [ ]:
MysecondList

In [ ]:
type(MysecondList)

In [ ]:
amx = ['how are you?',55, (3,4,5)] #list inside the list

In [ ]:
amx

In [ ]:
fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana'] 

In [ ]:
fruits.count('apple')

In [ ]:
range(15)

In [ ]:
list(range(15))

In [ ]:
x = [1,2,3,4,5,6,7]
x

In [ ]:
y = list(range(8)) 

In [ ]:
y

In [ ]:
z = list(range(1,8))

In [ ]:
z

In [48]:
a1 = list(range(5,8))
a1

[5, 6, 7]

In [ ]:
a2 = list(range(100,120)) 
a2

In [ ]:
a3 = list(range(10,20)) # 10 form right 20-1
a3

In [ ]:
a4 = list(range(10,20,3)) # adding 3 steps from 10 to 20

In [ ]:
a4

In [ ]:
xx = list(range(1,5,2))

In [ ]:
xx

In [ ]:
a5 = list(range(20,40,5))
a5

In [ ]:
# Now we can check how to read information from the list
w = ['a','e','i','o','u']

In [ ]:
w

In [ ]:
w[0]

In [ ]:
w[1]

In [ ]:
w[2]

In [ ]:
#if you have more no of list so how to know how many are there

len(w)

In [ ]:
# a,e,i,o,u
# 0,1,2,3,4
# -5,-4,-3,-2,-1

w[-4]

In [ ]:
w[0]

In [ ]:
# overwrite values
w

In [ ]:
w[2] = 10
w[2]

In [ ]:
w

In [ ]:
# slicing : operator
x = ['a', 'b', 'c', 'd', 'e' ,'f', 'g', 'h']
x

In [ ]:
x[2:7] #left side part always begins with 0 but right side always have to (no.-1)// 7-1

In [ ]:
x[-7:-1]

In [ ]:
x[2:7]

In [ ]:
x[-6:-1]

In [ ]:
#advanced slicing - [_:_:_] starting,ending,step
#if you specified : one more time then you get 3 spot last step is nothing but step
x

In [ ]:
x[0:8:2]

In [49]:
amxwam = ['A','B','C','D','E','F','G','H','I','J']
amxwam

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [50]:
amxwam[:]

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [51]:
amxwam[0:]

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [52]:
amxwam[1:]

['B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [ ]:
amxwam[2:] #------------------------

In [ ]:
amxwam[:7]

In [ ]:
amxwam[2:7]

In [ ]:
amxwam[-8:7]

In [ ]:
amxwam[-8:-3]

In [ ]:
# --- advanced slicing
amxwam[2:9:2]

In [ ]:
amxwam[::3]

In [ ]:
amxwam[::-2]

In [ ]:
amxwam[6:1:-1]

In [ ]:
amxwam

In [ ]:
amxwam[6:1:-2]

In [ ]:
#Tuples -- Immutable list or immutable sequence of values

t = (10,20,90)

In [ ]:
t

In [ ]:
t[1]

In [ ]:
#t[1]=30  #you are unable to change after declaration

In [ ]:
# Functions in python 

range(20, 31)


In [ ]:
list(range(20, 31))

In [ ]:
mylist1 = list(range(20, 31))

In [ ]:
mylist1

In [ ]:
print(mylist1)

In [ ]:
len(mylist1)

In [ ]:
type(mylist1)

In [ ]:
max(mylist1) 

In [ ]:
min(mylist1)

In [ ]:
max(1,450,234)

In [ ]:
min(1,450,234)

In [ ]:
# PACKAGES IN PYTHON
# PACKAGE - BOX, BLENDERS -FUNCTIONS, FRUITS - CLASS,DATA etc... 
# where & how to find the packages - github,googles Q & A query
# Install packages in anaconda prompt
# conda install package name // pip install package name
# import the packages
# from package import module
# give an example of tensorflow how to install in pip 

In [55]:
# NUMPY & ARRAY IN PYTHON
# numpy is the package you have to import 
# list is similar like to array
# numpy is also inbuild array in python

l = [23245, 27, 546, 215, -1234]
l

[23245, 27, 546, 215, -1234]

In [56]:
import numpy as np

In [59]:
a = np.array(l) # list is convert into arrays

In [60]:
a

array([23245,    27,   546,   215, -1234])

In [61]:
# what is the main difference between list & array
# you cannot create an array of different data types

b = np.array([12,455,True,'amxwam'])
b

array(['12', '455', 'True', 'amxwam'], dtype='<U11')

In [62]:
print(b)  #everything is converted into string

['12' '455' 'True' 'amxwam']


In [ ]:
l  #when you select. and then tab you get list of function

In [63]:
l.pop()

-1234

In [64]:
l

[23245, 27, 546, 215]

In [65]:
l

[23245, 27, 546, 215]

In [66]:
a


array([23245,    27,   546,   215, -1234])

In [67]:
a.mean()

4559.8

In [68]:
a

array([23245,    27,   546,   215, -1234])

In [ ]:
# slicing array

l

In [ ]:
l[1:]

In [ ]:
l[0:2]

In [ ]:
l[::2]

In [ ]:
a

In [ ]:
a[2:]

In [ ]:
a[2:4]

In [ ]:
b 

In [ ]:
b[0]

In [ ]:
c = a.copy() # when you create a copy of numpy array, modification can not be done both object array but in list it

In [ ]:
a

In [ ]:
c

In [ ]:
c[0] = 0

In [ ]:
c

In [ ]:
a

In [ ]:
a[0]

In [ ]:
a

In [ ]:
c

In [ ]:
m = [1,2,3]
m[0]

In [ ]:
m[0]= 81

In [ ]:
m

In [ ]:
n = list.copy(m) # when you create a copy of list, modification will done both object

In [ ]:
n

In [ ]:
m

In [ ]:
n[0]

# what we learned so far -- 
'''
1> list
2> create some list[],range()
3> using [] bracket
4> slicing list
5> Tuples
6> functions 
7> packages
8> Numpys & Arrays
9> slicing arrays'''

### PYTHOH END - 

-------